[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "lib_mangacollec"
version = "0.1.1"
description = "Lib Python pour l'API MangaCollec"
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}
authors = [
    {name = "ShooterDev", email = "vincentbleach@gmail.com.fr"}
]

dependencies = [
    "requests>=2.25.1"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "flake8",
    "ruff",
    "black",
    "mypy",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.black]
line-length = 120

[tool.flake8]
max-line-length = 120

[tool.pytest.ini_options]
pythonpath = ["src"]

[tool.ruff]
line-length = 120

[tool.mypy]
python_path = "src"